# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --no-progress
      - name: Build Lib
        run: yarn build
      - name: Release base
        if: contains('refs/heads/master', github.ref)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: sed -i 's/PKG_ROOT_VALUE/base/g' .releaserc && npx semantic-release
      - name: Release playwright
        if: contains('refs/heads/master', github.ref)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: sed -i 's/PKG_ROOT_VALUE/playwright/g' .releaserc && npx semantic-release
