# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.4.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --no-progress
      - name: Format check
        run: yarn format:check
      - name: Build Lib
        run: yarn build
      - name: Release
        if: contains('refs/heads/master refs/heads/feat-allow-to-pass-promise-as-response', github.ref)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
